project_id = "ucsxwhnscgbcshaghyrq"

[functions.twitter-integration]
verify_jwt = false

[functions.oauth-google-start]
verify_jwt = false

[functions.oauth-google-callback]
verify_jwt = false

[functions.oauth-google-disconnect]
verify_jwt = false

[functions.google-test-create-event]
verify_jwt = false

[functions.google-create-appointment-event]
verify_jwt = true

[functions.test-vertex-ai]
verify_jwt = true